/**
 * app.c  —  STM32F746G-DISCO  Main Application
 *
 * ── What this board does ────────────────────────────────────────────
 *   1. Reads ICM-20948 (9-DOF) at 102 Hz via I2C1
 *        I2C1: SCL = PB8 (Arduino SCL)   SDA = PB9 (Arduino SDA)
 *
 *   2. Runs Madgwick AHRS filter (quaternion orientation, 100 Hz)
 *        β = 0.033  (tuned for ICM-20948 @ 102 Hz)
 *
 *   3. Reads 4× RMCS-3070 encoders at 100 Hz
 *        FL : TIM5  A0(PA0=CH1)        + A1(PA1=CH2)
 *        FR : TIM2  D9(PA15=CH1)       + CN2p15(PB3=CH2)
 *        RL : TIM4  CN2p13(PB6=CH1)   + CN2p11(PB7=CH2)
 *        RR : TIM3  D3(PB4=CH1)        + CN2(PB5=CH2)
 *
 *   4. Drives 4× motors via TIM1 PWM (20 kHz) + direction GPIO
 *        FL : TIM1_CH1 → PA8(D10)     DIR → PG6(D2)
 *        FR : TIM1_CH2 → PE11(Morpho) DIR → PG7(D4)
 *        RL : TIM1_CH3 → PE13(Morpho) DIR → PI3(D7)
 *        RR : TIM1_CH4 → PE14(Morpho) DIR → PI2(D8)
 *
 *   5. Implements terrain-aware velocity safety layer (paper §III)
 *        IMU-based inclination risk  (Eq. 5,9)
 *        Terrain shake factor        (Eq. 6,7)
 *        Low-pass risk filter β=0.90 (Eq. 10)
 *        Nonlinear scaling (1−R)²    (Eq. 11)
 *        Hard E-stop at pitch>30°    (Eq. 12)
 *        Forward-flip detection (pitch_rate>30°/s + pitch>15°)
 *
 *   6. Receives /cmd_vel (geometry_msgs/Twist) from Nav2/SLAM on RPi
 *        Differential kinematics → per-wheel velocity targets
 *        Velocity PID (PI) closed-loop with encoder feedback
 *        Watchdog: stops motors if no /cmd_vel for 500 ms
 *
 *   7. Publishes via micro-ROS over USART6 (D1=TX, D0=RX) at 2 Mbaud:
 *        /imu/data          sensor_msgs/Imu              @ 100 Hz
 *        /wheel_ticks       std_msgs/Int32MultiArray      @  50 Hz
 *        /wheel_velocity    std_msgs/Float32MultiArray    @  50 Hz
 *
 * ── Reference ───────────────────────────────────────────────────────
 *   Safety layer:  Mourougane & Dhanalakshmi, "Terrain-Aware Velocity
 *   Regulation for Mobile Robots via Lightweight Execution-Level Safety
 *   Layer", SRM Institute of Science and Technology.
 *   Madgwick filter: Madgwick et al., IEEE ICORR 2011.
 *
 * ── CubeMX peripherals needed ───────────────────────────────────────
 *   I2C1  USART6  TIM5  TIM2  TIM4  TIM3  TIM1(PWM)
 *   GPIO: PG6 PG7 PI3 PI2 as outputs (motor direction)
 */

#include "app.h"
#include "icm20948.h"
#include "encoder.h"
#include "motor.h"
#include "pca9685.h"
#include "madgwick.h"
#include "microros_transport.h"
#include "lcd_display.h"
#include "main.h"

/* micro-ROS */
#include <rcl/rcl.h>
#include <rcl/error_handling.h>
#include <rclc/rclc.h>
#include <rclc/executor.h>
#include <rmw_microros/rmw_microros.h>
#include <sensor_msgs/msg/imu.h>
#include <std_msgs/msg/int32_multi_array.h>
#include <std_msgs/msg/float32_multi_array.h>
#include <geometry_msgs/msg/twist.h>
#include <uxr/client/transport.h>

#include <math.h>
#include <string.h>

/* ── HAL handles (generated by CubeMX in main.c) ────────────────── */
extern I2C_HandleTypeDef  hi2c1;    /* SCL=PB8  SDA=PB9                   */
extern TIM_HandleTypeDef  htim5;    /* FL encoder : A0(PA0=CH1)+A1(PA1=CH2) */
extern TIM_HandleTypeDef  htim2;    /* FR encoder : D9(PA15=CH1)+CN2p15(PB3=CH2) */
extern TIM_HandleTypeDef  htim4;    /* RL encoder : CN2p13(PB6=CH1)+CN2p11(PB7=CH2) */
extern TIM_HandleTypeDef  htim3;    /* RR encoder : D3(PB4=CH1)+CN2(PB5=CH2) */
extern TIM_HandleTypeDef  htim1;    /* Motor PWM  : TIM1 CH1-CH4 (20 kHz)  */
extern UART_HandleTypeDef huart6;   /* D1(PC6=TX)  D0(PC7=RX)  2 Mbaud    */

/* ── Timing ─────────────────────────────────────────────────────── */
#define LCD_PUB_PERIOD_MS    100   /*  10 Hz — LCD refresh            */
#define IMU_PERIOD_MS         10   /* 100 Hz — Madgwick + safety      */
#define ENC_PERIOD_MS         10   /* 100 Hz — encoder + motor PID    */
#define IMU_PUB_PERIOD_MS     10   /* 100 Hz — /imu/data publish      */
#define ENC_PUB_PERIOD_MS     20   /*  50 Hz — /wheel_ticks publish   */
#define CALIB_SAMPLES        200   /*   ~2 s at 100 Hz — gyro bias    */
#define MADGWICK_BETA       0.033f

/* ── Safety parameters — Mourougane & Dhanalakshmi paper ─────────
 *
 * Eq.5:  θ_w = W_PITCH × |pitch| + W_ROLL × |roll|   [degrees]
 * Eq.9:  R_incl = clamp((θ_w − THETA_SAFE) / (THETA_CRIT − THETA_SAFE), 0,1)
 * Eq.10: R_f = BETA × R_f_prev + (1−BETA) × R_raw
 * Eq.11: speed_scale = (1 − R_f)²
 * Eq.12: pitch > ESTOP_PITCH OR roll > ESTOP_ROLL → stop
 */
#define SAFETY_W_PITCH       0.7f    /* slope risk weight (pitch)          */
#define SAFETY_W_ROLL        0.3f    /* lateral instability weight (roll)  */
#define SAFETY_THETA_SAFE    10.0f   /* safe zone upper limit [deg]        */
#define SAFETY_THETA_CRIT    30.0f   /* E-stop boundary [deg]              */
#define SAFETY_W_INCL        0.7f    /* inclination fraction in R_raw      */
#define SAFETY_W_SHAKE       0.3f    /* vibration   fraction in R_raw      */
#define SAFETY_LPF_BETA      0.90f   /* low-pass β (paper §III-C)          */
#define SAFETY_ESTOP_PITCH   30.0f   /* hard E-stop pitch threshold [deg]  */
#define SAFETY_ESTOP_ROLL    40.0f   /* hard E-stop roll  threshold [deg]  */
/* Forward-flip detection (paper §VI future work) */
#define SAFETY_FLIP_RATE     (30.0f * 0.017453293f)  /* 30 deg/s → rad/s */
#define SAFETY_FLIP_PITCH    (15.0f * 0.017453293f)  /* 15 deg   → rad   */

/* ── cmd_vel watchdog ────────────────────────────────────────────── */
#define CMD_VEL_TIMEOUT_MS   500    /* stop motors if ROS silent > 500 ms */

/* ── Motor velocity PI controller ────────────────────────────────── */
#define MOTOR_KP     0.5f
#define MOTOR_KI     0.1f
#define MOTOR_ILIMIT (MOTOR_MAX_SPEED_MMPS * 0.5f)   /* anti-windup cap */

/* ── Noise covariance (ICM-20948 datasheet) ──────────────────────── */
/* Gyro  : 0.015 dps/√Hz @ 100 Hz → σ = 0.00262 rad/s               */
/* Accel : 230 µg/√Hz   @ 100 Hz → σ = 0.02256 m/s²                 */
#define GY_COV   (0.00262f * 0.00262f)
#define AC_COV   (0.02256f * 0.02256f)
#define OR_COV    0.0001f

#define UROS_OK(fn)  do { if ((fn) != RCL_RET_OK) Error_Handler(); } while(0)

/* ── micro-ROS objects ───────────────────────────────────────────── */
static rcl_allocator_t  alloc;
static rclc_support_t   support;
static rcl_node_t       node;
static rclc_executor_t  executor;

static rcl_publisher_t    pub_imu;
static rcl_publisher_t    pub_ticks;
static rcl_publisher_t    pub_vel;
static rcl_subscription_t sub_cmd_vel;

static sensor_msgs__msg__Imu              msg_imu;
static std_msgs__msg__Int32MultiArray     msg_ticks;
static std_msgs__msg__Float32MultiArray   msg_vel;
static geometry_msgs__msg__Twist          msg_cmd_vel;

static int32_t  tick_buf[ENC_NUM];
static float    vel_buf [ENC_NUM];
static char     frame_id_buf[] = "imu_link";

/* ── Sensor state ────────────────────────────────────────────────── */
static ICM20948_Data  imu;
static ICM20948_Calib calib;
static Madgwick_t     ahrs;

/* ── Safety state ────────────────────────────────────────────────── */
static float g_risk_filtered = 0.0f;   /* Eq.10 low-pass output            */
static float g_safety_scale  = 1.0f;   /* Eq.11 speed scale = (1−R)²       */

/* ── Motor / cmd_vel state ───────────────────────────────────────── */
static float    g_target_mmps[MOTOR_NUM] = {0};   /* raw targets from ROS  */
static float    g_pid_integral[MOTOR_NUM] = {0};  /* PI integrator state   */
static uint32_t g_cmd_last_ms = 0;                /* watchdog timestamp    */

/* ═══════════════════════════════════════════════════════════════════
 *  cmd_vel subscription callback
 *  Called by rclc_executor_spin_some() when /cmd_vel arrives.
 *  Converts Twist → per-wheel velocity targets (differential drive).
 * ═══════════════════════════════════════════════════════════════════ */
static void cmd_vel_callback(const void *msg_in)
{
    const geometry_msgs__msg__Twist *tw =
        (const geometry_msgs__msg__Twist *)msg_in;

    /*
     * Differential-drive (skid-steer) kinematics:
     *   linear.x  [m/s]   → vx_mmps
     *   angular.z [rad/s] → wz
     *   L = ENC_WHEELBASE_MM
     *
     *   v_left  = vx − wz × L/2     (applies to FL and RL)
     *   v_right = vx + wz × L/2     (applies to FR and RR)
     */
    float vx   = (float)tw->linear.x  * 1000.0f;   /* m/s → mm/s */
    float wz   = (float)tw->angular.z;              /* rad/s      */
    float hL   = ENC_WHEELBASE_MM * 0.5f;           /* mm         */

    float vl = vx - wz * hL;   /* left  side mm/s */
    float vr = vx + wz * hL;   /* right side mm/s */

    g_target_mmps[MOTOR_FL] = vl;
    g_target_mmps[MOTOR_FR] = vr;
    g_target_mmps[MOTOR_RL] = vl;
    g_target_mmps[MOTOR_RR] = vr;

    g_cmd_last_ms = HAL_GetTick();   /* reset watchdog */
}

/* ═══════════════════════════════════════════════════════════════════
 *  IMU safety layer  —  paper §III-C / §III-D
 *
 *  Runs at 100 Hz immediately after each Madgwick update.
 *  Writes g_safety_scale which is applied in motor_pid_update().
 *  On hard E-stop, calls Motor_StopAll() directly for zero latency.
 * ═══════════════════════════════════════════════════════════════════ */
static void update_safety(void)
{
    /* Euler angles from Madgwick (populated by Madgwick_GetEuler) */
    float pitch_deg = ahrs.pitch * (180.0f / 3.14159265f);
    float roll_deg  = ahrs.roll  * (180.0f / 3.14159265f);
    float pitch_abs = (pitch_deg < 0.0f) ? -pitch_deg : pitch_deg;
    float roll_abs  = (roll_deg  < 0.0f) ? -roll_deg  : roll_deg;

    /* ── Eq.12: Hard E-stop — check first for minimum latency ──── */
    /* Forward-flip: rapid pitch rate while already tilted (paper §VI) */
    float pitch_rate = imu.gy - calib.gy_bias;   /* bias-removed [rad/s] */
    if (pitch_rate < 0.0f) pitch_rate = -pitch_rate;

    if ((pitch_abs >= SAFETY_ESTOP_PITCH)       ||
        (roll_abs  >= SAFETY_ESTOP_ROLL)         ||
        (pitch_rate > SAFETY_FLIP_RATE && ahrs.pitch > SAFETY_FLIP_PITCH))
    {
        g_risk_filtered = 1.0f;
        g_safety_scale  = 0.0f;
        Motor_StopAll();   /* hardware stop — no latency through PID */
        return;
    }

    /* ── Eq.5: weighted inclination ──────────────────────────── */
    float theta_w = SAFETY_W_PITCH * pitch_abs + SAFETY_W_ROLL * roll_abs;

    /* ── Eq.9: normalize to [0,1] between safe and critical zones */
    float r_incl = (theta_w - SAFETY_THETA_SAFE) /
                   (SAFETY_THETA_CRIT - SAFETY_THETA_SAFE);
    if (r_incl < 0.0f) r_incl = 0.0f;
    if (r_incl > 1.0f) r_incl = 1.0f;

    /* ── Eq.6-7: terrain shake from accel magnitude deviation ─── */
    float a_mag = sqrtf(imu.ax*imu.ax + imu.ay*imu.ay + imu.az*imu.az);
    float g_ref = (calib.gravity > 9.0f) ? calib.gravity : 9.80665f;
    float r_shake = (a_mag - g_ref) / g_ref;
    if (r_shake < 0.0f) r_shake = -r_shake;   /* absolute deviation */
    if (r_shake > 1.0f) r_shake  = 1.0f;

    /* ── Eq.8: combined terrain risk ─────────────────────────── */
    float r_raw = SAFETY_W_INCL * r_incl + SAFETY_W_SHAKE * r_shake;
    if (r_raw > 1.0f) r_raw = 1.0f;

    /* ── Eq.10: low-pass filter  β = 0.90 ───────────────────── */
    g_risk_filtered = SAFETY_LPF_BETA  * g_risk_filtered +
                      (1.0f - SAFETY_LPF_BETA) * r_raw;

    /* ── Eq.11: nonlinear velocity scale  v_cmd = v_max × (1−R)² */
    float s = 1.0f - g_risk_filtered;
    g_safety_scale = s * s;
}

/* ═══════════════════════════════════════════════════════════════════
 *  Motor velocity PI  —  100 Hz
 *  Safety scale is applied to the target before the PI runs so the
 *  integrator tracks the already-reduced setpoint.
 * ═══════════════════════════════════════════════════════════════════ */
static void motor_pid_update(float dt_s)
{
    for (int i = 0; i < MOTOR_NUM; i++) {
        float target   = g_target_mmps[i] * g_safety_scale;
        float measured = Encoder_VelMmps((uint8_t)i);
        float error    = target - measured;

        g_pid_integral[i] += error * dt_s;
        if (g_pid_integral[i] >  MOTOR_ILIMIT) g_pid_integral[i] =  MOTOR_ILIMIT;
        if (g_pid_integral[i] < -MOTOR_ILIMIT) g_pid_integral[i] = -MOTOR_ILIMIT;

        float cmd = target
                  + MOTOR_KP * error
                  + MOTOR_KI * g_pid_integral[i];

        Motor_Set((Motor_ID)i, cmd);
    }
}

/* ═══════════════════════════════════════════════════════════════════
 *  micro-ROS setup
 * ═══════════════════════════════════════════════════════════════════ */
static void uros_setup(void)
{
    rmw_uros_set_custom_transport(
        true, NULL,
        transport_open, transport_close,
        transport_write, transport_read);

    alloc = rcutils_get_default_allocator();

    /* Wait until micro_ros_agent is running on the Raspberry Pi */
    while (rmw_uros_ping_agent(200, 10) != RMW_RET_OK)
        HAL_Delay(200);

    UROS_OK(rclc_support_init(&support, 0, NULL, &alloc));
    UROS_OK(rclc_node_init_default(&node, "stm32f7_node", "terrain_bot", &support));

    /* ── Publishers ── */
    UROS_OK(rclc_publisher_init_best_effort(
        &pub_imu, &node,
        ROSIDL_GET_MSG_TYPE_SUPPORT(sensor_msgs, msg, Imu), "/imu/data"));
    UROS_OK(rclc_publisher_init_best_effort(
        &pub_ticks, &node,
        ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Int32MultiArray), "/wheel_ticks"));
    UROS_OK(rclc_publisher_init_best_effort(
        &pub_vel, &node,
        ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Float32MultiArray), "/wheel_velocity"));

    /* ── Subscriber: /cmd_vel from Nav2 / SLAM ── */
    UROS_OK(rclc_subscription_init_best_effort(
        &sub_cmd_vel, &node,
        ROSIDL_GET_MSG_TYPE_SUPPORT(geometry_msgs, msg, Twist), "/cmd_vel"));

    /* Executor: 1 subscription handle */
    UROS_OK(rclc_executor_init(&executor, &support.context, 1, &alloc));
    UROS_OK(rclc_executor_add_subscription(
        &executor, &sub_cmd_vel, &msg_cmd_vel,
        cmd_vel_callback, ON_NEW_DATA));

    /* ── Message buffer wiring ── */
    msg_ticks.data.data     = tick_buf;
    msg_ticks.data.size     = ENC_NUM;
    msg_ticks.data.capacity = ENC_NUM;
    msg_vel.data.data       = vel_buf;
    msg_vel.data.size       = ENC_NUM;
    msg_vel.data.capacity   = ENC_NUM;

    msg_imu.header.frame_id.data     = frame_id_buf;
    msg_imu.header.frame_id.size     = 8;
    msg_imu.header.frame_id.capacity = 9;

    /* Covariance matrices — diagonal entries, set once */
    memset(msg_imu.orientation_covariance,         0, sizeof(double) * 9);
    memset(msg_imu.angular_velocity_covariance,    0, sizeof(double) * 9);
    memset(msg_imu.linear_acceleration_covariance, 0, sizeof(double) * 9);
    msg_imu.orientation_covariance[0]         = OR_COV;
    msg_imu.orientation_covariance[4]         = OR_COV;
    msg_imu.orientation_covariance[8]         = OR_COV;
    msg_imu.angular_velocity_covariance[0]    = GY_COV;
    msg_imu.angular_velocity_covariance[4]    = GY_COV;
    msg_imu.angular_velocity_covariance[8]    = GY_COV;
    msg_imu.linear_acceleration_covariance[0] = AC_COV;
    msg_imu.linear_acceleration_covariance[4] = AC_COV;
    msg_imu.linear_acceleration_covariance[8] = AC_COV;
}

/* ── Publish /imu/data ───────────────────────────────────────────── */
static void publish_imu(void)
{
    uint64_t ns = (uint64_t)HAL_GetTick() * 1000000ULL;
    msg_imu.header.stamp.sec     = (int32_t)(ns / 1000000000ULL);
    msg_imu.header.stamp.nanosec = (uint32_t)(ns % 1000000000ULL);

    msg_imu.orientation.w = ahrs.q0;
    msg_imu.orientation.x = ahrs.q1;
    msg_imu.orientation.y = ahrs.q2;
    msg_imu.orientation.z = ahrs.q3;

    msg_imu.angular_velocity.x = imu.gx - calib.gx_bias;
    msg_imu.angular_velocity.y = imu.gy - calib.gy_bias;
    msg_imu.angular_velocity.z = imu.gz - calib.gz_bias;

    msg_imu.linear_acceleration.x = imu.ax;
    msg_imu.linear_acceleration.y = imu.ay;
    msg_imu.linear_acceleration.z = imu.az;

    rcl_publish(&pub_imu, &msg_imu, NULL);
}

/* ── Publish all 4 encoder channels ─────────────────────────────── */
static void publish_encoders(void)
{
    for (int i = 0; i < ENC_NUM; i++) {
        tick_buf[i] = Encoder_Ticks((uint8_t)i);
        vel_buf[i]  = Encoder_VelMmps((uint8_t)i);
    }
    rcl_publish(&pub_ticks, &msg_ticks, NULL);
    rcl_publish(&pub_vel,   &msg_vel,   NULL);
}

/* ═══════════════════════════════════════════════════════════════════
 *  App entry point  —  never returns
 * ═══════════════════════════════════════════════════════════════════ */
void App_Run(void)
{
    /* 1. LCD */
    LCD_Display_Init();

    /* 2. ICM-20948 IMU */
    if (ICM20948_Init(&hi2c1) != HAL_OK)
        Error_Handler();   /* check I2C wiring — see PIN_CONNECTIONS.txt */

    /* 3. All 4 encoders */
    Encoder_Init(&htim5, &htim2, &htim4, &htim3);

    /* 4. PCA9685 I2C PWM expander — must come before Motor_Init */
    PCA9685_Init(&hi2c1);

    /* 5. All 4 motor PWM outputs (via PCA9685) */
    Motor_Init(&htim1);

    /* 6. Madgwick orientation filter */
    Madgwick_Init(&ahrs, MADGWICK_BETA);

    /* 7. micro-ROS — blocks until Raspberry Pi agent responds */
    uros_setup();

    /* 8. Gyro bias calibration — keep robot completely still (~2 s) */
    memset(&calib, 0, sizeof(calib));
    while (!calib.done) {
        LCD_Display_Update(&ahrs, 0);   /* show CALIB on LCD */
        if (ICM20948_Read(&hi2c1, &imu) == HAL_OK)
            ICM20948_Calibrate(&imu, &calib, CALIB_SAMPLES);
        HAL_Delay(IMU_PERIOD_MS);
    }

    /* 9. Seed Madgwick with accel-derived roll/pitch */
    {
        float ax = imu.ax, ay = imu.ay, az = imu.az;
        float rn = 1.0f / sqrtf(ax*ax + ay*ay + az*az);
        ax *= rn; ay *= rn; az *= rn;
        float r = atan2f(ay, az);
        float p = atan2f(-ax, sqrtf(ay*ay + az*az));
        ahrs.q0 = cosf(r/2) * cosf(p/2);
        ahrs.q1 = sinf(r/2) * cosf(p/2);
        ahrs.q2 = cosf(r/2) * sinf(p/2);
        ahrs.q3 = -sinf(r/2) * sinf(p/2);
        ahrs.initialised = true;
    }

    /* 10. Arm cmd_vel watchdog */
    g_cmd_last_ms = HAL_GetTick();

    /* 11. Main loop */
    uint32_t t_imu     = HAL_GetTick();
    uint32_t t_enc     = HAL_GetTick();
    uint32_t t_pub_imu = HAL_GetTick();
    uint32_t t_pub_enc = HAL_GetTick();
    uint32_t t_lcd     = HAL_GetTick();

    while (1) {
        uint32_t now = HAL_GetTick();

        /* ── Read + filter IMU @ 100 Hz → safety layer ── */
        if (now - t_imu >= IMU_PERIOD_MS) {
            float dt = (float)(now - t_imu) * 0.001f;
            t_imu = now;

            if (ICM20948_Read(&hi2c1, &imu) == HAL_OK) {
                float gx = imu.gx - calib.gx_bias;
                float gy = imu.gy - calib.gy_bias;
                float gz = imu.gz - calib.gz_bias;

                if (imu.mx != 0.0f || imu.my != 0.0f || imu.mz != 0.0f)
                    Madgwick_UpdateMARG(&ahrs, gx, gy, gz,
                                        imu.ax, imu.ay, imu.az,
                                        imu.mx, imu.my, imu.mz, dt);
                else
                    Madgwick_UpdateIMU(&ahrs, gx, gy, gz,
                                       imu.ax, imu.ay, imu.az, dt);

                /* Safety layer — paper §III, runs at same rate as IMU */
                update_safety();
            }
        }

        /* ── Encoders + motor PI @ 100 Hz ── */
        if (now - t_enc >= ENC_PERIOD_MS) {
            float dt = (float)(now - t_enc) * 0.001f;
            t_enc = now;

            Encoder_Update();

            /* cmd_vel watchdog: stop if ROS goes silent */
            if (now - g_cmd_last_ms > CMD_VEL_TIMEOUT_MS) {
                memset(g_target_mmps,  0, sizeof(g_target_mmps));
                memset(g_pid_integral, 0, sizeof(g_pid_integral));
                Motor_StopAll();
            } else {
                motor_pid_update(dt);
            }
        }

        /* ── Publish IMU @ 100 Hz ── */
        if (now - t_pub_imu >= IMU_PUB_PERIOD_MS) {
            t_pub_imu = now;
            publish_imu();
        }

        /* ── Publish encoders (all 4) @ 50 Hz ── */
        if (now - t_pub_enc >= ENC_PUB_PERIOD_MS) {
            t_pub_enc = now;
            publish_encoders();
        }

        /* ── LCD refresh @ 10 Hz ── */
        if (now - t_lcd >= LCD_PUB_PERIOD_MS) {
            t_lcd = now;
            LCD_Display_Update(&ahrs, 1);
        }

        /* Spin micro-ROS executor — processes incoming /cmd_vel */
        rclc_executor_spin_some(&executor, RCL_MS_TO_NS(0));
    }
}
